"use strict";(self.webpackChunklaravel_workflow=self.webpackChunklaravel_workflow||[]).push([[6957],{3905:(e,t,n)=>{n.d(t,{Zo:()=>u,kt:()=>d});var r=n(7294);function i(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function o(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);t&&(r=r.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,r)}return n}function a(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?o(Object(n),!0).forEach((function(t){i(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function l(e,t){if(null==e)return{};var n,r,i=function(e,t){if(null==e)return{};var n,r,i={},o=Object.keys(e);for(r=0;r<o.length;r++)n=o[r],t.indexOf(n)>=0||(i[n]=e[n]);return i}(e,t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(r=0;r<o.length;r++)n=o[r],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(i[n]=e[n])}return i}var c=r.createContext({}),s=function(e){var t=r.useContext(c),n=t;return e&&(n="function"==typeof e?e(t):a(a({},t),e)),n},u=function(e){var t=s(e.components);return r.createElement(c.Provider,{value:t},e.children)},p="mdxType",y={inlineCode:"code",wrapper:function(e){var t=e.children;return r.createElement(r.Fragment,{},t)}},f=r.forwardRef((function(e,t){var n=e.components,i=e.mdxType,o=e.originalType,c=e.parentName,u=l(e,["components","mdxType","originalType","parentName"]),p=s(n),f=i,d=p["".concat(c,".").concat(f)]||p[f]||y[f]||o;return n?r.createElement(d,a(a({ref:t},u),{},{components:n})):r.createElement(d,a({ref:t},u))}));function d(e,t){var n=arguments,i=t&&t.mdxType;if("string"==typeof e||i){var o=n.length,a=new Array(o);a[0]=f;var l={};for(var c in t)hasOwnProperty.call(t,c)&&(l[c]=t[c]);l.originalType=e,l[p]="string"==typeof e?e:i,a[1]=l;for(var s=2;s<o;s++)a[s]=n[s];return r.createElement.apply(null,a)}return r.createElement.apply(null,n)}f.displayName="MDXCreateElement"},2906:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>c,contentTitle:()=>a,default:()=>p,frontMatter:()=>o,metadata:()=>l,toc:()=>s});var r=n(7462),i=(n(7294),n(3905));const o={sidebar_position:9},a="Failures and Recovery",l={unversionedId:"failures-and-recovery",id:"failures-and-recovery",title:"Failures and Recovery",description:"Handling Exceptions",source:"@site/docs/failures-and-recovery.md",sourceDirName:".",slug:"/failures-and-recovery",permalink:"/docs/failures-and-recovery",draft:!1,editUrl:"https://github.com/laravel-workflow/laravel-workflow.github.io/edit/main/docs/failures-and-recovery.md",tags:[],version:"current",sidebarPosition:9,frontMatter:{sidebar_position:9},sidebar:"tutorialSidebar",previous:{title:"Testing",permalink:"/docs/testing"},next:{title:"How It Works",permalink:"/docs/how-it-works"}},c={},s=[{value:"Handling Exceptions",id:"handling-exceptions",level:2},{value:"Non-retryable Exceptions",id:"non-retryable-exceptions",level:2},{value:"Failing Activities",id:"failing-activities",level:2},{value:"Recovery Process",id:"recovery-process",level:2}],u={toc:s};function p(e){let{components:t,...n}=e;return(0,i.kt)("wrapper",(0,r.Z)({},u,n,{components:t,mdxType:"MDXLayout"}),(0,i.kt)("h1",{id:"failures-and-recovery"},"Failures and Recovery"),(0,i.kt)("h2",{id:"handling-exceptions"},"Handling Exceptions"),(0,i.kt)("p",null,"When an activity throws an exception, the workflow won't immediately be informed. Instead, it waits until the number of ",(0,i.kt)("inlineCode",{parentName:"p"},"$tries")," has been exhausted. The system will keep retrying the activity based on its retry policy. If you want the exception to be immediately sent to the workflow upon a failure, you can set the number of ",(0,i.kt)("inlineCode",{parentName:"p"},"$tries")," to 1."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-php"},"use Exception;\nuse Workflow\\Activity;\n\nclass MyActivity extends Activity\n{\n    public $tries = 1;\n\n    public function execute()\n    {\n        throw new Exception();\n    }\n}\n")),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-php"},"use Exception;\nuse Workflow\\ActivityStub;\nuse Workflow\\Workflow;\n\nclass MyWorkflow extends Workflow\n{\n    public function execute()\n    {\n        try {\n            $result = yield ActivityStub::make(MyActivity::class);\n        } catch (Exception) {\n            // handle the exception here\n        }\n    }\n}\n")),(0,i.kt)("h2",{id:"non-retryable-exceptions"},"Non-retryable Exceptions"),(0,i.kt)("p",null,"In certain cases, you may encounter exceptions that should not be retried. These are referred to as non-retryable exceptions. When an activity throws a non-retryable exception, the workflow will immediately mark the activity as failed and stop retrying."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-php"},"use Workflow\\Activity;\nuse Workflow\\Exceptions\\NonRetryableException;\n\nclass MyNonRetryableActivity extends Activity\n{\n    public function execute()\n    {\n        throw new NonRetryableException('This is a non-retryable error');\n    }\n}\n")),(0,i.kt)("h2",{id:"failing-activities"},"Failing Activities"),(0,i.kt)("p",null,"The default value for ",(0,i.kt)("inlineCode",{parentName:"p"},"$tries")," is 0 which means to retry forever. This is because the retry policy includes a backoff function which increases the delay between each retry attempt. This gives you time to fix the error without creating too many attempts."),(0,i.kt)("p",null,"There are two types of failures that can occur in a activity: recoverable failures and non-recoverable failures. Recoverable failures are temporary and can be resolved without intervention, such as a timeout or temporary network failure. Non-recoverable failures require manual intervention, such as a deployment or code change."),(0,i.kt)("h2",{id:"recovery-process"},"Recovery Process"),(0,i.kt)("p",null,"The general process to fix a failing activity is:"),(0,i.kt)("ol",null,(0,i.kt)("li",{parentName:"ol"},"Check the logs for the activity that is failing and look for any errors or exceptions that are being thrown."),(0,i.kt)("li",{parentName:"ol"},"Identify the source of the error and fix it in the code."),(0,i.kt)("li",{parentName:"ol"},"Deploy the fix to the server where the queue is running."),(0,i.kt)("li",{parentName:"ol"},"Restart the queue worker to pick up the new code."),(0,i.kt)("li",{parentName:"ol"},"Wait for the activity to automatically retry and ensure that it is now completing successfully without errors."),(0,i.kt)("li",{parentName:"ol"},"If the activity continues to fail, repeat the process until the issue is resolved.")),(0,i.kt)("p",null,"This allows you to keep the workflow in a running status even while an activity is failing. After you fix the failing activity, the workflow will finish in a completed status. A workflow with a failed status means that all activity ",(0,i.kt)("inlineCode",{parentName:"p"},"$tries")," have been exhausted and the exception wasn't handled."))}p.isMDXComponent=!0}}]);